### PR TITLE
Improve styles of icon for instant translate

### PR DESCRIPTION
**Pull request by AlexWayfer**
Was:

image

Became:

image

### CODE REVIEW

**Comment by ixrock** [comment]
I don't think your option looks better. Sorry, but cannot be merged.

**Comment by AlexWayfer** [comment]
Do you think that symbol getting out beyond the edge of the circle is better?

Or a pixel ("step") circle?

**Comment by ixrock** [comment]
What is pixel-step circle? o_O
Ok, regarding to symbol going beyond the border, it can be hidden with `overflow: hidden;`

**Comment by AlexWayfer** [comment]
> What is pixel-step circle? o_O

Sorry, I mean aliasing.

> Ok, regarding to symbol going beyond the border, it can be hidden with overflow: hidden;

This is "duck tape".

**Comment by ixrock** [comment]
Oh, I see. But on my mac the border looks perfectly :)
Anyway, `box-shadow` seems to have the same "aliasing" problem on windows, isn't it?

**Comment by AlexWayfer** [comment]
> Anyway, box-shadow seems to have the same "aliasing" problem on windows, isn't it?

It's not windows :) Just 108.79 PPI (2560x1440px, 27").

Yes, but a little less.

**Pull request closed without merging**
