### PR TITLE
Create messages.json

### PR DESCRIPTION
**Pull request by Sijera**
Serbian

### CODE REVIEW

**Comment by ixrock** [comment]
Thanks!

**Comment by ixrock** [comment]
BTW, could you please also translate common description of app for the store?
You can find english version here:
https://chrome.google.com/webstore/detail/xtranslate/gfgpkepllngchpmcippidfhmbhlljhoo

**Comment by Sijera** [comment]
Description text attached
[desc.txt](https://github.com/ixrock/XTranslate/files/681493/desc.txt)

**Comment by ixrock** [comment]
Cool, thanks!

**Pull request merged**
