### PR TITLE
Update Serbian translation

### PR DESCRIPTION
**Pull request by rammba**
Hi @ixrock, I must say that I'm surprised that your extension has Serbian language. Serbian is not widely known language and I'm trying to make it present on different places.
In this PR, I've fixed some small typos and translated missing text. I hope you will find my changes sufficient.

### CODE REVIEW

**Comment by ixrock** [comment]
@rammba thanks for contribution, this will reach chrome store a bit later. 
Yeah, I know it's not too famous language and I don't speak it personally. This is @Sijera who added initial Serbian translations in 8357fe2495ca162e21c1b8034fa461a7b43f3038 I guess.

_P.S Serbian icon fix already available in chrome extensions store._

**Comment by rammba** [comment]
Great! If @Sijera is still active user, we should update comment in serbian file to mention it also.

**Comment by Sijera** [comment]
Yes, I am author :)

**Comment by rammba** [comment]
I'm glad to hear that! Feel free to check my changes and potentially improve translation. You can also list yourself as an author in the file comment.
Also, I thought to add Serbian latin as well. What do you think about it?

**Comment by ixrock** [comment]
@rammba you can do that if you like :)

**Comment by Sijera** [comment]
Great, feel free to continue this work, in the meantime I've moved on to other projects. :)

**Pull request merged**
